# LAB 01.01 - Practice submission

In [1]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()


replicating local resources


In [15]:
import inspect
from local.lib.rlxmoocapi import session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

logging in as santiago.herrera6@udea.edu.co... please wait

-------------
using course session ai4eng.v1::open
success!! you are logged in
-------------


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [4]:

def suma_matrices(a,b):
    ## --- TU CODIGO AQUI ---
    result = a+b
    return result



comprueba manualmente tu código

In [7]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print ('la matriz A es:',a)
print ('la matriz B es:',b)
print ('la suma de A con B es:',suma_matrices(a,b))

la matriz A es: [[1 6]
 [3 0]
 [5 1]]
la matriz B es: [[9 7]
 [3 8]
 [4 4]]
la suma de A con B es: [[10 13]
 [ 6  8]
 [ 9  5]]


#### registra tu solución en línea

In [16]:
student.submit_task(globals(), task_id="task_01");

In [17]:
T = np.array([[1,3],[4,6]])
H = np.array([[4,5],[1,2]])
suma=suma_matrices(T,H)
print ('la matriz T es:\n',T)
print ('la matriz H es:\n',H)
print('La suma entre T y H es:\n',suma)

la matriz T es:
 [[1 3]
 [4 6]]
la matriz H es:
 [[4 5]
 [1 2]]
La suma entre T y H es:
 [[5 8]
 [5 8]]


### Ejercicio 2: Realiza un cálculo

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [18]:
import numpy as np
rlist = np.random.randint(100, size=10)
rlist

array([15, 12, 65, 28, 13, 81, 66, 27, 69, 66])

#### tu solución

In [19]:
avg = np.mean(rlist)
avg

np.float64(44.2)

#### registra tu solución en línea

In [20]:
student.submit_task(globals(), task_id="task_02");

In [ ]:
44.2